import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';

export const DATA_MODULE = 'somewhere:data';
export const DATA_VIRTUAL_ID = '\0somewhere:data';
export const DATA_DECLARATION_FILE = '__somewhere_data.d.ts';
export const GENERATED_DATA_HEADER = '// Generated by Somewhere from db/schema.ts. Do not edit.\n';

// The `sw.endpoint` input types are vendored from the platform compiler
// (ENDPOINT_DECLARATION below). The compiler deliberately does not declare the
// `sw` global itself (browser source has none; its deploy check recognises
// `sw.endpoint` in function modules), so the local typecheck adds only that.
const SW_ENDPOINT_GLOBAL = `declare const sw: {
  // docs({ topic: 'sw.endpoint' }). Throw an Error with .status and .code
  // for a typed error response; anything else is 500 HANDLER_ERROR.
  endpoint<const Schema extends SomewhereEndpointBodySchema | undefined = undefined, Auth extends SomewhereEndpointAuth = 'none'>(
    config: SomewhereEndpointConfig<Auth, Schema>,
  ): (req: Request, sw: SomewhereRuntimeContext) => Promise<Response>;
};
`;

export interface DeclaredDataClient {
  contract_digest: string;
  declaration: string;
  runtime: string;
  manifest: { version: number; contract_digest: string; tables: unknown[]; declaration: string };
}
// This file is bundled from the platform's parser and compiler; no second DSL.
const require = createRequire(import.meta.url);

interface DeclaredDataGenerator {
  generateFromFiles(files: Record<string, string>): DeclaredDataClient | undefined;
  declaredTablesFromFiles(files: Record<string, string>): string;
  filesDeclarationFromFiles(files: Record<string, string>): string | undefined;
  SCHEMA_DECLARATION: string;
  RUNTIME_CONTEXT_DECLARATION: string;
  ENDPOINT_DECLARATION: string;
  FILES_DECLARATION_FILE: string;
}
export interface LocalDeclaredData {
  client: DeclaredDataClient | undefined;
  declarationPath: string;
  /** Present only when db/schema.ts declares file collections (somewhere:files). */
  filesDeclarationPath: string | undefined;
  schemaPath: string;
}

/** The generated somewhere:files declaration; the compiler's own file name. */
export const FILES_DECLARATION_FILE = (require('../../runtime/declared-data.cjs') as DeclaredDataGenerator).FILES_DECLARATION_FILE;

function generatedContents(path: string): string | undefined {
  const previous = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
  if (previous !== undefined && !previous.startsWith(GENERATED_DATA_HEADER)) {
    throw new Error(`Cannot overwrite ${path}; this path is reserved for a generated declaration.`);
  }
  return previous;
}

/** Source only: no evaluation, backend requests, npm installs or customer build. */
export function prepareDeclaredData(projectDir: string): LocalDeclaredData | undefined {
  const schemaPath = join(projectDir, 'db', 'schema.ts');
  // Vite apps normally include src rather than their root in the editor's config.
  const declarationDir = existsSync(join(projectDir, 'src')) ? join(projectDir, 'src') : projectDir;
  const declarationPath = join(declarationDir, DATA_DECLARATION_FILE);
  const filesPath = join(declarationDir, FILES_DECLARATION_FILE);
  const previous = existsSync(declarationPath) ? readFileSync(declarationPath, 'utf8') : undefined;
  const previousFiles = existsSync(filesPath) ? readFileSync(filesPath, 'utf8') : undefined;
  if (!existsSync(schemaPath)) {
    if (previous?.startsWith(GENERATED_DATA_HEADER)) rmSync(declarationPath);
    if (previousFiles?.startsWith(GENERATED_DATA_HEADER)) rmSync(filesPath);
    return undefined;
  }
  generatedContents(declarationPath);
  generatedContents(filesPath);
  let client: DeclaredDataClient | undefined;
  // Server reads and writes of the declared tables are typed from the same schema.
  let tables: string;
  let filesDeclaration: string | undefined;
  const generator = require('../../runtime/declared-data.cjs') as DeclaredDataGenerator;
  try {
    const files = { 'db/schema.ts': readFileSync(schemaPath, 'utf8') };
    client = generator.generateFromFiles(files);
    tables = generator.declaredTablesFromFiles(files);
    filesDeclaration = generator.filesDeclarationFromFiles(files);
  }
  catch (error) {
    // Do not leave stale permissions and field types looking current in editors.
    if (previous !== undefined) rmSync(declarationPath);
    if (previousFiles !== undefined) rmSync(filesPath);
    throw error;
  }
  const declaration = GENERATED_DATA_HEADER + generator.RUNTIME_CONTEXT_DECLARATION + tables
    + generator.ENDPOINT_DECLARATION + SW_ENDPOINT_GLOBAL + generator.SCHEMA_DECLARATION + (client?.declaration ?? '');
  if (declaration !== previous) writeFileSync(declarationPath, declaration);
  // Only declared collections exist on somewhere:files; with none, the module is
  // left undeclared so an import of it fails the check exactly as the deploy does.
  if (filesDeclaration === undefined) {
    if (previousFiles !== undefined) rmSync(filesPath);
  } else if (GENERATED_DATA_HEADER + filesDeclaration !== previousFiles) {
    writeFileSync(filesPath, GENERATED_DATA_HEADER + filesDeclaration);
  }
  return { client, declarationPath, filesDeclarationPath: filesDeclaration === undefined ? undefined : filesPath, schemaPath };
}

interface DataDevServer {
  watcher: {
    add(path: string): void;
    on(event: string, callback: (path: string) => void): void;
    off(event: string, callback: (path: string) => void): void;
  };
  moduleGraph: { getModuleById(id: string): unknown; invalidateModule(module: unknown): void };
  ws: { send(payload: unknown): void };
}

export function declaredDataPlugin(projectDir: string) {
  const schemaPath = resolve(projectDir, 'db', 'schema.ts');
  let prepared = prepareDeclaredData(projectDir);
  let failure: Error | undefined;
  let cleanup: (() => void) | undefined;
  return {
    name: 'somewhere-declared-data',
    enforce: 'pre' as const,
    resolveId(id: string) { return id === DATA_MODULE ? DATA_VIRTUAL_ID : undefined; },
    load(id: string) {
      if (id !== DATA_VIRTUAL_ID) return undefined;
      if (failure) throw failure;
      if (!prepared?.client?.manifest.tables.length) {
        throw new Error('somewhere:data requires db/schema.ts with explicit client permissions.');
      }
      return prepared.client.runtime;
    },
    configureServer(server: DataDevServer) {
      // Watching the parent also notices a schema added after dev starts.
      server.watcher.add(join(projectDir, 'db'));
      const changed = (path: string) => {
        if (resolve(path) !== schemaPath) return;
        try { prepared = prepareDeclaredData(projectDir); failure = undefined; }
        catch (error) { prepared = undefined; failure = error instanceof Error ? error : new Error(String(error)); }
        const module = server.moduleGraph.getModuleById(DATA_VIRTUAL_ID);
        if (module) server.moduleGraph.invalidateModule(module);
        if (failure) server.ws.send({ type: 'error', err: { message: failure.message, stack: failure.stack ?? '', plugin: 'somewhere-declared-data', id: schemaPath } });
        else server.ws.send({ type: 'full-reload' });
      };
      for (const event of ['add', 'change', 'unlink']) server.watcher.on(event, changed);
      cleanup = () => { for (const event of ['add', 'change', 'unlink']) server.watcher.off(event, changed); };
    },
    closeBundle() { cleanup?.(); },
  };
}
