import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';

export const DATA_MODULE = 'somewhere:data';
export const DATA_VIRTUAL_ID = '\0somewhere:data';
export const DATA_DECLARATION_FILE = '__somewhere_data.d.ts';
export const GENERATED_DATA_HEADER = '// Generated by Somewhere from db/schema.ts. Do not edit.\n';

// The global `sw.endpoint` wrapper every deployed function can use. Mirrors the
// platform's __sw_init.mjs pipeline (worker/src/utils/function-bundle.ts):
// auth, body schema, rate limit, cors, then handler({ body, user, ... }, sw).
// Written here so projects never hand-declare the platform's globals.
export const ENDPOINT_DECLARATION = `
interface SomewhereEndpointUser {
  id: string;
  email?: string | null;
  display_name?: string | null;
  role?: string;
  [key: string]: unknown;
}
type __SomewhereEndpointLeaf = 'string' | 'email' | 'number' | 'boolean' | 'array' | 'object';
interface SomewhereEndpointBodySchema {
  readonly [field: string]: __SomewhereEndpointLeaf | \`\${__SomewhereEndpointLeaf}?\` | SomewhereEndpointBodySchema;
}
type __SomewhereEndpointValue<T> =
  T extends 'string' | 'email' ? string : T extends 'number' ? number : T extends 'boolean' ? boolean
    : T extends 'array' ? unknown[] : T extends 'object' ? Record<string, unknown> : never;
type __SomewhereEndpointBody<S> = {
  -readonly [K in keyof S as S[K] extends \`\${string}?\` ? never : K]:
    S[K] extends string ? __SomewhereEndpointValue<S[K]> : __SomewhereEndpointBody<S[K]>;
} & {
  -readonly [K in keyof S as S[K] extends \`\${string}?\` ? K : never]?:
    S[K] extends \`\${infer T}?\` ? __SomewhereEndpointValue<T> | null : never;
};
type SomewhereEndpointAuth = 'none' | 'optional' | 'required';
interface SomewhereEndpointInput<Auth extends SomewhereEndpointAuth, Body> {
  body: Body;
  user: Auth extends 'required' ? SomewhereEndpointUser : SomewhereEndpointUser | null;
  headers: Headers;
  params: Record<string, string>;
  request: Request;
}
interface SomewhereEndpointConfig<Auth extends SomewhereEndpointAuth, Schema extends SomewhereEndpointBodySchema | undefined> {
  auth?: Auth;
  body?: Schema;
  rateLimit?: \`\${number}/\${'second' | 'minute' | 'hour' | 'day'}\${'' | 's'}\`;
  cors?: 'same-origin' | '*' | readonly string[];
  handler(
    input: SomewhereEndpointInput<Auth, Schema extends SomewhereEndpointBodySchema ? __SomewhereEndpointBody<Schema> : null>,
    sw: SomewhereRuntimeContext,
  ): unknown;
}
declare const sw: {
  // docs({ topic: 'sw.endpoint' }). Throw an Error with .status and .code
  // for a typed error response; anything else is 500 HANDLER_ERROR.
  endpoint<const Schema extends SomewhereEndpointBodySchema | undefined = undefined, Auth extends SomewhereEndpointAuth = 'none'>(
    config: SomewhereEndpointConfig<Auth, Schema>,
  ): (req: Request, sw: SomewhereRuntimeContext) => Promise<Response>;
};
`;

export interface DeclaredDataClient {
  contract_digest: string;
  declaration: string;
  runtime: string;
  manifest: { version: number; contract_digest: string; tables: unknown[]; declaration: string };
}
interface DeclaredDataGenerator {
  generateFromFiles(files: Record<string, string>): DeclaredDataClient | undefined;
  declaredTablesFromFiles(files: Record<string, string>): string;
  SCHEMA_DECLARATION: string;
  RUNTIME_CONTEXT_DECLARATION: string;
}
// This file is bundled from the platform's parser and compiler; no second DSL.
const require = createRequire(import.meta.url);

export interface LocalDeclaredData {
  client: DeclaredDataClient | undefined;
  declarationPath: string;
  schemaPath: string;
}

/** Source only: no evaluation, backend requests, npm installs or customer build. */
export function prepareDeclaredData(projectDir: string): LocalDeclaredData | undefined {
  const schemaPath = join(projectDir, 'db', 'schema.ts');
  // Vite apps normally include src rather than their root in the editor's config.
  const declarationDir = existsSync(join(projectDir, 'src')) ? join(projectDir, 'src') : projectDir;
  const declarationPath = join(declarationDir, DATA_DECLARATION_FILE);
  const previous = existsSync(declarationPath) ? readFileSync(declarationPath, 'utf8') : undefined;
  if (!existsSync(schemaPath)) {
    if (previous?.startsWith(GENERATED_DATA_HEADER)) rmSync(declarationPath);
    return undefined;
  }
  if (previous !== undefined && !previous.startsWith(GENERATED_DATA_HEADER)) {
    throw new Error(`Cannot overwrite ${declarationPath}; this path is reserved for the generated data declaration.`);
  }
  let client: DeclaredDataClient | undefined;
  // Server reads and writes of the declared tables are typed from the same schema.
  let tables: string;
  const generator = require('../../runtime/declared-data.cjs') as DeclaredDataGenerator;
  try {
    const files = { 'db/schema.ts': readFileSync(schemaPath, 'utf8') };
    client = generator.generateFromFiles(files);
    tables = generator.declaredTablesFromFiles(files);
  }
  catch (error) {
    // Do not leave stale permissions and field types looking current in editors.
    if (previous !== undefined) rmSync(declarationPath);
    throw error;
  }
  const declaration = GENERATED_DATA_HEADER + generator.RUNTIME_CONTEXT_DECLARATION + tables + ENDPOINT_DECLARATION + generator.SCHEMA_DECLARATION + (client?.declaration ?? '');
  if (declaration !== previous) writeFileSync(declarationPath, declaration);
  return { client, declarationPath, schemaPath };
}

interface DataDevServer {
  watcher: {
    add(path: string): void;
    on(event: string, callback: (path: string) => void): void;
    off(event: string, callback: (path: string) => void): void;
  };
  moduleGraph: { getModuleById(id: string): unknown; invalidateModule(module: unknown): void };
  ws: { send(payload: unknown): void };
}

export function declaredDataPlugin(projectDir: string) {
  const schemaPath = resolve(projectDir, 'db', 'schema.ts');
  let prepared = prepareDeclaredData(projectDir);
  let failure: Error | undefined;
  let cleanup: (() => void) | undefined;
  return {
    name: 'somewhere-declared-data',
    enforce: 'pre' as const,
    resolveId(id: string) { return id === DATA_MODULE ? DATA_VIRTUAL_ID : undefined; },
    load(id: string) {
      if (id !== DATA_VIRTUAL_ID) return undefined;
      if (failure) throw failure;
      if (!prepared?.client?.manifest.tables.length) {
        throw new Error('somewhere:data requires db/schema.ts with explicit client permissions.');
      }
      return prepared.client.runtime;
    },
    configureServer(server: DataDevServer) {
      // Watching the parent also notices a schema added after dev starts.
      server.watcher.add(join(projectDir, 'db'));
      const changed = (path: string) => {
        if (resolve(path) !== schemaPath) return;
        try { prepared = prepareDeclaredData(projectDir); failure = undefined; }
        catch (error) { prepared = undefined; failure = error instanceof Error ? error : new Error(String(error)); }
        const module = server.moduleGraph.getModuleById(DATA_VIRTUAL_ID);
        if (module) server.moduleGraph.invalidateModule(module);
        if (failure) server.ws.send({ type: 'error', err: { message: failure.message, stack: failure.stack ?? '', plugin: 'somewhere-declared-data', id: schemaPath } });
        else server.ws.send({ type: 'full-reload' });
      };
      for (const event of ['add', 'change', 'unlink']) server.watcher.on(event, changed);
      cleanup = () => { for (const event of ['add', 'change', 'unlink']) server.watcher.off(event, changed); };
    },
    closeBundle() { cleanup?.(); },
  };
}
