import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';

export const DATA_MODULE = 'somewhere:data';
export const DATA_VIRTUAL_ID = '\0somewhere:data';
export const DATA_DECLARATION_FILE = '__somewhere_data.d.ts';
const GENERATED_HEADER = '// Generated by Somewhere from db/schema.ts. Do not edit.\n';

export interface DeclaredDataClient {
  contract_digest: string;
  declaration: string;
  runtime: string;
  manifest: { version: number; contract_digest: string; tables: unknown[]; declaration: string };
}
interface DeclaredDataGenerator {
  generateFromFiles(files: Record<string, string>): DeclaredDataClient | undefined;
  SCHEMA_DECLARATION: string;
}
// This file is bundled from the platform's parser and compiler; no second DSL.
const generator = createRequire(import.meta.url)('../../runtime/declared-data.cjs') as DeclaredDataGenerator;

export interface LocalDeclaredData {
  client: DeclaredDataClient | undefined;
  declarationPath: string;
  schemaPath: string;
}

/** Source only: no evaluation, backend requests, npm installs or customer build. */
export function prepareDeclaredData(projectDir: string): LocalDeclaredData | undefined {
  const schemaPath = join(projectDir, 'db', 'schema.ts');
  // Vite apps normally include src rather than their root in the editor's config.
  const declarationDir = existsSync(join(projectDir, 'src')) ? join(projectDir, 'src') : projectDir;
  const declarationPath = join(declarationDir, DATA_DECLARATION_FILE);
  const previous = existsSync(declarationPath) ? readFileSync(declarationPath, 'utf8') : undefined;
  if (!existsSync(schemaPath)) {
    if (previous?.startsWith(GENERATED_HEADER)) rmSync(declarationPath);
    return undefined;
  }
  if (previous !== undefined && !previous.startsWith(GENERATED_HEADER)) {
    throw new Error(`Cannot overwrite ${declarationPath}; this path is reserved for the generated data declaration.`);
  }
  let client: DeclaredDataClient | undefined;
  try { client = generator.generateFromFiles({ 'db/schema.ts': readFileSync(schemaPath, 'utf8') }); }
  catch (error) {
    // Do not leave stale permissions and field types looking current in editors.
    if (previous !== undefined) rmSync(declarationPath);
    throw error;
  }
  const declaration = GENERATED_HEADER + generator.SCHEMA_DECLARATION + (client?.declaration ?? '');
  if (declaration !== previous) writeFileSync(declarationPath, declaration);
  return { client, declarationPath, schemaPath };
}

interface DataDevServer {
  watcher: {
    add(path: string): void;
    on(event: string, callback: (path: string) => void): void;
    off(event: string, callback: (path: string) => void): void;
  };
  moduleGraph: { getModuleById(id: string): unknown; invalidateModule(module: unknown): void };
  ws: { send(payload: unknown): void };
}

export function declaredDataPlugin(projectDir: string) {
  const schemaPath = resolve(projectDir, 'db', 'schema.ts');
  let prepared = prepareDeclaredData(projectDir);
  let failure: Error | undefined;
  let cleanup: (() => void) | undefined;
  return {
    name: 'somewhere-declared-data',
    enforce: 'pre' as const,
    resolveId(id: string) { return id === DATA_MODULE ? DATA_VIRTUAL_ID : undefined; },
    load(id: string) {
      if (id !== DATA_VIRTUAL_ID) return undefined;
      if (failure) throw failure;
      if (!prepared?.client?.manifest.tables.length) {
        throw new Error('somewhere:data requires db/schema.ts with explicit client permissions.');
      }
      return prepared.client.runtime;
    },
    configureServer(server: DataDevServer) {
      // Watching the parent also notices a schema added after dev starts.
      server.watcher.add(join(projectDir, 'db'));
      const changed = (path: string) => {
        if (resolve(path) !== schemaPath) return;
        try { prepared = prepareDeclaredData(projectDir); failure = undefined; }
        catch (error) { prepared = undefined; failure = error instanceof Error ? error : new Error(String(error)); }
        const module = server.moduleGraph.getModuleById(DATA_VIRTUAL_ID);
        if (module) server.moduleGraph.invalidateModule(module);
        if (failure) server.ws.send({ type: 'error', err: { message: failure.message, stack: failure.stack ?? '', plugin: 'somewhere-declared-data', id: schemaPath } });
        else server.ws.send({ type: 'full-reload' });
      };
      for (const event of ['add', 'change', 'unlink']) server.watcher.on(event, changed);
      cleanup = () => { for (const event of ['add', 'change', 'unlink']) server.watcher.off(event, changed); };
    },
    closeBundle() { cleanup?.(); },
  };
}
