/**
 * Build a local `.env` file body from a project's env-var KEY list.
 *
 * Values are intentionally blank: the platform never returns env-var values
 * from any API route — they are decrypted into the deployed function bundle at
 * deploy time and never leave that boundary. So `somewhere env pull` writes the
 * exact set of keys the project expects (grouped by scope) with empty values
 * as a local key inventory. Backend values remain configured on the deployed
 * project; frontend hot reload does not supply values to its backend.
 */
export interface EnvKey {
  key: string;
  scope?: string;
}

export function buildEnvTemplate(keys: EnvKey[], opts: { projectId?: string } = {}): string {
  const header = [
    '# Generated by `somewhere env pull`.',
    '# These are the env vars your project expects. Values are NOT included —',
    '# the platform never returns secret values. Backend values stay on the',
    '# deployed project. This blank key inventory is git/deploy',
    '# ignored and never leaves your machine.',
  ];
  if (opts.projectId) header.push(`# project: ${opts.projectId}`);

  const lines = [...header, ''];

  // Preserve incoming order but keep keys with the same name once. The list
  // endpoint already sorts by key_name, so the output is stable + diffable.
  const seen = new Set<string>();
  for (const k of keys) {
    if (!k.key || seen.has(k.key)) continue;
    seen.add(k.key);
    const scopeNote = k.scope && k.scope !== 'all' ? `  # scope: ${k.scope}` : '';
    lines.push(`${k.key}=${scopeNote}`);
  }

  return lines.join('\n') + '\n';
}
