import { Command } from 'commander';
import { ApiClient, CliApiError } from '../lib/client.js';
import { getToken, loadProjectConfig } from '../lib/config.js';
import { dim, error, red, table, teal, timeAgo, yellow } from '../lib/output.js';
import { chooseProjectRef, projectRefConflictMessage } from '../lib/project-ref.js';

interface ErrorRow {
  endpoint?: string | null;
  method?: string | null;
  status_code?: number | null;
  error_code?: string | null;
  error_message?: string | null;
  /** Did the code CHOOSE this outcome? A handler that answers 401 to a
   *  signed-out request is working; an uncaught throw is not. Older platform
   *  versions do not send this — an absent value is treated as an exception,
   *  which is what the view assumed about everything before. */
  kind?: 'exception' | 'refusal' | null;
  source?: 'api' | 'server' | 'function' | null;
  created_at: string;
}

/** A refusal the app chose, as opposed to something that broke. */
const isRefusal = (r: ErrorRow): boolean => r.kind === 'refusal';

// This project-runtime-only endpoint records query observations generated by
// the platform. An app function or a caller's ordinary API failure stays visible
// under its existing kind, even if its message contains INTERNAL_ERROR.
const isPlatformDiagnostic = (r: ErrorRow): boolean => r.source === 'api'
  && r.method === 'POST' && r.endpoint === '/v1/db/query-observations'
  && (r.status_code ?? 0) >= 500;

// A caller leaving is ordinary traffic; ambiguous 499s and handler failures stay visible.
const isClientDisconnect = (r: ErrorRow): boolean => r.status_code === 499
  && r.source === 'function' && r.kind === 'refusal'
  && (r.error_code === 'CLIENT_DISCONNECTED'
    || (r.error_code === 'HTTP_499' && r.error_message?.startsWith('CLIENT_DISCONNECTED:') === true));

export function registerErrors(program: Command) {
  program
    .command('errors [project]')
    .description(
      'Show what recently went wrong in a project — the curated 24h view ' +
        '(endpoint, status, error, time). The fastest way to see what is ' +
        'breaking in production without digging through raw logs. Rows are ' +
        'split into EXCEPTIONS (nobody chose it — an uncaught throw or a 5xx) ' +
        'and REFUSALS (your handler answered 4xx on purpose, e.g. a 401 from ' +
        'your own auth gate). Platform-generated diagnostics are labeled separately. ' +
        'Use --exceptions to hide your handler\'s deliberate refusals.',
    )
    .option('--project <ref>', 'Project ID, name, slug, or subdomain — the same flag every other command takes. The positional form still works.')
    .option('--limit <n>', 'Max rows to show (default 20, max 100)', '20')
    .option('--exceptions', 'Hide the 4xx your own handlers returned on purpose; keep exceptions and platform diagnostics.')
    .option('--json', 'Print rows as JSON; platform-generated diagnostics include diagnostic_origin.')
    .action(async (projectArg: string | undefined, opts) => {
      const client = new ApiClient(getToken());

      const chosen = chooseProjectRef(projectArg, opts.project);
      if (chosen.kind === 'conflict') {
        error(projectRefConflictMessage(chosen));
        process.exit(1);
      }
      let projectId = chosen.kind === 'ref' ? chosen.ref : undefined;
      if (!projectId) {
        const config = loadProjectConfig();
        if (!config) {
          error('No project. Pass a project ID (positionally or with --project) or run from a linked directory.');
          process.exit(1);
        }
        projectId = config.project_id;
      }

      const limit = Math.min(parseInt(String(opts.limit), 10) || 20, 100);

      let rows: ErrorRow[];
      try {
        const result = await client.call<{ errors: ErrorRow[] }>(
          'GET',
          '/errors/recent',
          undefined,
          { project_id: projectId, limit },
        );
        rows = result.errors ?? [];
      } catch (err) {
        if (err instanceof CliApiError) {
          error(`${err.message} ${dim(`[${err.code}${err.statusCode ? `, HTTP ${err.statusCode}` : ''}]`)}`, err);
        } else {
          error(err instanceof Error ? err.message : String(err), err);
        }
        process.exit(1);
      }

      const refusals = rows.filter(isRefusal).length;
      if (opts.exceptions) rows = rows.filter((r) => !isRefusal(r));

      if (opts.json) {
        console.log(JSON.stringify(rows.map(r => isPlatformDiagnostic(r)
          ? { ...r, diagnostic_origin: 'platform' } : r), null, 2));
        return;
      }

      const disconnected = rows.filter(isClientDisconnect).length;
      rows = rows.filter(r => !isClientDisconnect(r));
      const disconnectedNotice = `${disconnected} client disconnect${disconnected === 1 ? '' : 's'} collapsed — use --json to see every row.`;
      if (!rows.length && disconnected) {
        console.log(dim(`  ${disconnectedNotice}`));
        return;
      }

      if (!rows.length) {
        // A window with nothing but refusals is a healthy window — say what is
        // actually there rather than reporting a bare zero.
        if (refusals && opts.exceptions) {
          console.log(dim(`  Nothing broke in the recent window. 🎉 (${refusals} request${refusals === 1 ? '' : 's'} your app refused on purpose — drop --exceptions to see them.)`));
          return;
        }
        console.log(dim('  No errors in the recent window. 🎉'));
        return;
      }

      const tableRows = rows.map((r) => {
        const status = r.status_code ?? 0;
        const statusStr = status >= 500 ? red(String(status)) : status >= 400 ? yellow(String(status)) : String(status || '—');
        const where = `${r.method ? `${r.method} ` : ''}${r.endpoint ?? '—'}`;
        const what = r.error_code && r.error_code !== 'FUNCTION_ERROR'
          ? `${r.error_code}: ${truncate(r.error_message)}`
          : truncate(r.error_message);
        // A 401 your own handler returned is your auth gate working. Calling it
        // an exception is what made this view fill with normal traffic on any
        // app with a login.
        const kind = isPlatformDiagnostic(r) ? 'platform diagnostic'
          : isRefusal(r) ? dim('refused') : 'exception';
        return [kind, statusStr, where, what, timeAgo(r.created_at)];
      });

      table(['Kind', 'Status', 'Endpoint', 'Error', 'When'], tableRows);
      const platformDiagnostics = rows.filter(isPlatformDiagnostic).length;
      const exceptions = rows.length - rows.filter(isRefusal).length - platformDiagnostics;
      const counts = opts.exceptions
        ? `${exceptions} exception${exceptions === 1 ? '' : 's'}`
        : `${exceptions} exception${exceptions === 1 ? '' : 's'}, ${rows.filter(isRefusal).length} refused on purpose`;
      const diagnosticCount = platformDiagnostics
        ? `, ${platformDiagnostics} platform diagnostic${platformDiagnostics === 1 ? '' : 's'}` : '';
      console.log(dim(`\n  ${counts}${diagnosticCount} — ${teal('somewhere logs --level error')} for full detail.`));
      if (disconnected) console.log(dim(`  ${disconnectedNotice}`));
    });
}

function truncate(s: string | null | undefined, max = 80): string {
  if (!s) return '—';
  const flat = s.replace(/\s+/g, ' ').trim();
  return flat.length > max ? flat.slice(0, max - 1) + '…' : flat;
}
